export const FETCH_VOTERS = "FETCH_VOTERS";
export const FETCHING_VOTERS = "FETCHING_VOTERS";
export const FETCHED_VOTERS = "FETCHED_VOTERS";

export const FETCH_CAMPAIGN = "FETCH_CAMPAIGN";
export const FETCHED_CAMPAIGN = "FETCHED_CAMPAIGN";
export const UPDATE_CAMPAIGN = "UPDATE_CAMPAIGN"

export const SELECT_VOTER = "SELECT_VOTER";
export const VOTER_CONTACTED = "VOTER_CONTACTED";
export const VOTER_NO_ANSWER = "VOTER_NO_ANSWER"

export const POST_SURVEY = "POST_SURVEY";
export const POSTED_SURVEY = "POSTED_SURVEY";

export const CLEAR_STATE = "CLEAR_STATE"
