export const FETCH_VOTERS = "FETCH_VOTERS";
export const FETCHING_VOTERS = "FETCHING_VOTERS";
export const FETCHED_VOTERS = "FETCHED_VOTERS";

export const FETCH_CAMPAIGN = "FETCH_CAMPAIGN";
export const FETCHED_CAMPAIGN = "FETCHED_CAMPAIGN";

export const SELECT_VOTER = "SELECT_VOTER";
export const VOTER_CONTACTED = "VOTER_CONTACTED";

export const POST_SURVEY = "POST_SURVEY";
export const POSTED_SURVEY = "POSTED_SURVEY";
